{{- if .Values.job.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
    name: {{ .Values.job.metadataname }}
    annotations:
    {{- .Values.hooks.annotations | toYaml | nindent 6 }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.job.name }}
          image: "{{ .Values.job.repository }}:{{ .Values.job.imagetag }}"
          command: 
            - build.sh
          volumeMounts:
          - mountPath: / 
            name: build-script
            subPath: build.sh
          restartPolicy: Never
          env:
            - name: BRANCH
              value: $ARGOCD_APP_SOURCE_TARGET_REVISION
            - name: APP_NAME
              value: $ARGOCD_APP_NAME
            - name: REVISION
              value: $ARGOCD_APP_REVISION
      volumes:
        - hostPath:
            path: scripts
          name: build-script
  backoffLimit: 2
  {{- end }}
